### ISSUE TITLE
Getting azure storage working with boost::asio framework

### ISSUE THREAD

**Issue by jade2k11598** [Azure/azure-storage-cpplite#113]
Hi,
I have an application that uses the `boost::asio` framework for a pool of threads, which works asynchronously.  Is there a way of getting the azure-storage-cpplite to work asynchronously?  I notice that the public interfaces return futures, which the examples given, just calls its `get()` function to acquire results, which will block (not desirable for asynchronous programming).  Just looking for a way for this to work asynchronously such that when making the request to `put` a blob, one can provide it a handler to trigger when a response of that put is received.

**Comment by Jinming-Hu** [comment]
Hi @jade2k11598 , APIs in this cpplite sdk aren't guaranteed to be async. Returning `std::future` is a bad design, due to lack of consideration. This cpplite sdk is going to be deprecated in favor of [Track2 storage sdk](https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/storage). So I suggest you switch to track2 sdk and start a new thread (or use a thread pool) for each put request.

**Comment by jade2k11598** [comment]
Thanks @Jinming-Hu.  Will look at the referenced alternative.
